services:
  redis-production:
    image: redis/redis-stack-server:6.2.6-v10
    command: [ "redis-server", "--requirepass", "ADD_YOUR_PASSWORD" ]
    restart: always

  server-production:
    build:
      context: .
      dockerfile: Dockerfile-production
      target: final
      args:
        - REACT_APP_ENV=production
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - REDIS_HOST=redis-production
      - REDIS_PORT=6379
      - REDIS_PASSWORD=ADD_YOUR_PASSWORD
      - ASPNETCORE_HTTP_PORTS=5114
    restart: always
    depends_on:
      - redis-production

  reverse-proxy:
    image: nginx:1.25.3
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always
    depends_on:
      - server-production